Adiciona função para limpar strings
DadosAbertosDeFeira/laia pull request #56
Opened 2021-10-31 12:41 UTC by turquetti

@anapaulagomes,

Subi o que fiz até agora pra você conseguir entender melhor o problema 😢 

Criei uma função `clean_string` para tirar acentuações, espaços e substitui-los por underscore para resolver a questão do Status que nós temos! E eventualmente usarmos para qualquer outro campo no futuro!

Porém, como havia comentado, o atual problema aqui é que, a biblioteca `unidecode` não é carregada. É como se ela não estivesse instalado, mas ela já consta nas dependências!

2021-10-31 14:16 UTC, Laerte commented
@turquetti O que acha de usar o módulo nativo [unicodedata](https://docs.python.org/3/library/unicodedata.html)? Assim não precisamos ter mais uma dependência externa.

```python
def clean_string(string):
     new_string = string.lower().replace(" ", "_")
     normalized = normalize('NFKD', new_string)
     normalized = normalized.encode('ascii', 'ignore')
     return normalized.decode()
```

2021-10-31 14:18 UTC, turquetti commented
@Laerte caramba, boa! Vou ajustar aqui! Obrigadão!!!!

2021-10-31 19:01 UTC, anapaulagomes requested changes

2021-11-01 16:51 UTC, turquetti commented on pyproject.toml
> +
Sim! Com o docker-compose up --build realmente funciona. Mas com os comandos do poetry não faria sentido funcionar também? 😕

2021-11-01 18:41 UTC, anapaulagomes commented on pyproject.toml
> +
Depende do erro. Se o erro for que ele não consegue conectar ao banco, é um problema de configuração e não da dependência. Foi eirro de configuração o que deu rodando local.

2023-03-26 22:23 UTC, merged